random_seed: 42

dataset:

  coco_categories_map:
    1: "person"
    17: "cat"
    18: "dog"
  coco_train_annotations_url: "http://images.cocodataset.org/annotations/annotations_trainval2017.zip"
  coco_archive_train_filename: 'annotations/instances_train2017.json'
  coco_archive_val_filename: 'annotations/instances_val2017.json'
  
  raw_files_folder: "data/raw_input"
  